import { supabase,isConfigured } from '../lib/supabase/client';
import { Product,PaginatedProducts } from '../types';
const CACHE_KEY='mare_catalog_cache'; const BRANCH_ID='871e7074-dbea-48dc-ae1e-f1570b5e0047';
const slugify=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');
class ProductService{
 private readCache():Product[]{try{return JSON.parse(localStorage.getItem(CACHE_KEY)||'[]');}catch{return[];}}
 private writeCache(p:Product[]){try{localStorage.setItem(CACHE_KEY,JSON.stringify(p));}catch{}}
 getProductsSync():Product[]{try{const raw=localStorage.getItem(CACHE_KEY);const parsed=raw?JSON.parse(raw):[];return Array.isArray(parsed)?parsed:[];}catch{return[];}}
 getProductBySlugSync(slug:string){return this.getProductsSync().find(p=>p.slug===slug);}
 async hydrate():Promise<Product[]>{try{const products=await this.getAllProducts();if(typeof window!=='undefined')window.dispatchEvent(new Event('mare_products_updated'));return products;}catch(error){console.warn('CRM catalog unavailable; using cached products.',error);return this.getProductsSync();}}
 private async stockMap(ids:string[]){if(!ids.length)return new Map<string,number>();const{data,error}=await supabase.from('inventory').select('product_id,quantity').eq('branch_id',BRANCH_ID).in('product_id',ids);if(error)throw error;const m=new Map<string,number>();for(const r of data||[])m.set(r.product_id,(m.get(r.product_id)||0)+Number(r.quantity||0));return m;}
 private map(r:any,s:Map<string,number>):Product{const stock=s.get(r.id)||0;const active=r.status!=='inactive';const available=active&&stock>0;return{id:r.id,slug:`${slugify(r.name)}-${String(r.id).slice(-6)}`,nombre:r.name,precioMN:Number(r.price||0),imagenes:r.image?[r.image]:[],descripcionCorta:'',descripcionCompleta:'',categoria:r.category_id||'',categoria_id:r.category_id||undefined,categoriaNombre:r.categories?.name,etiquetas:[],disponibilidad:available?'disponible':'agotado',available,sku:r.sku||undefined,stockVisual:stock,stock,stock_actual:stock,precioCUP:Number(r.price||0),stock_tracking:true,stock_quantity:stock,reserved_quantity:0,low_stock_threshold:Number(r.min_stock_alert||0),availability_status:available?'available':'out_of_stock',nuevo:false,oferta:false,destacado:false,masVendido:false,fechaCreacion:r.created_at,orden:0,activo:active,opcionesVariantes:[],variantes:[]};}
 private query(){return supabase.from('products').select('id,name,sku,price,category_id,status,min_stock_alert,image,created_at,categories(id,name)');}
 async getPaginatedProducts(o:any={}):Promise<PaginatedProducts>{if(!isConfigured){const p=this.readCache();return{products:p,total:p.length,hasMore:false,nextOffset:p.length};}const{limit=12,offset=0,category,search,minPrice,maxPrice,sort='newest'}=o;let q:any=this.query().eq('status','active');if(search?.trim())q=q.or(`name.ilike.%${search.trim()}%,sku.ilike.%${search.trim()}%,barcode.ilike.%${search.trim()}%`);if(minPrice!=null)q=q.gte('price',minPrice);if(maxPrice!=null)q=q.lte('price',maxPrice);if(category)q=q.eq('category_id',category);q=sort==='price-asc'?q.order('price',{ascending:true}):sort==='price-desc'?q.order('price',{ascending:false}):q.order('created_at',{ascending:false});const{data,error}=await q.range(offset,offset+limit-1);if(error)throw error;const stocks=await this.stockMap((data||[]).map((p:any)=>p.id));const products=(data||[]).map((p:any)=>this.map(p,stocks));if(offset===0)this.writeCache(products);return{products,total:offset+products.length,hasMore:products.length===limit,nextOffset:offset+products.length};}
 async getAllProducts():Promise<Product[]>{if(!isConfigured)return this.readCache();const{data,error}=await this.query().eq('status','active').order('created_at',{ascending:false});if(error)throw error;const stocks=await this.stockMap((data||[]).map((p:any)=>p.id));const mapped=(data||[]).map((p:any)=>this.map(p,stocks));this.writeCache(mapped);return mapped;}
 async getProducts(){return this.getAllProducts();} async getProductById(id:string){if(!isConfigured)return this.readCache().find(p=>p.id===id);const{data,error}=await this.query().eq('id',id).maybeSingle();if(error||!data)return undefined;return this.map(data,await this.stockMap([id]));} async getProductBySlug(slug:string){return(await this.getAllProducts()).find(p=>p.slug===slug);} async getProductsByCategory(id:string){return(await this.getAllProducts()).filter(p=>p.categoria===id);}
 async createProduct():Promise<never>{throw new Error('read only');} async updateProduct():Promise<never>{throw new Error('read only');} async deleteProduct():Promise<never>{throw new Error('read only');}
}
export const productService=new ProductService(); export const getProducts=()=>productService.getProducts(); export const getProductById=(id:string)=>productService.getProductById(id); export const getProductBySlug=(slug:string)=>productService.getProductBySlug(slug);
